---
driver:
  name: vagrant
  provider: <%= ENV['KITCHEN_PROVIDER'] || 'virtualbox' %>

transport:
  name: sftp

driver_config:
    customize:
#      cpus: 2
      memory: 1024

provisioner:
  name: ansible_playbook
  roles_path: ../../roles
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
#  name: chef_solo

platforms:
  - name: ubuntu-16.04
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8588}]
  - name: ubuntu-14.04
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8588}]
## No package matching 'php5-redis' is available
#  - name: ubuntu-12.04
## test for agent windows/wixl ? no image available
#  - name: ubuntu-15.10
## mig-scheduler issue w rights on database
  - name: centos-7.1
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8589}]

suites:
  - name: default
    run_list:
    attributes:
  - name: nginx
    run_list:
    attributes:
        misp_webserver: 'nginx'
    includes:
      - ubuntu-14.04
      - centos-7.1
    provisioner:
      name: ansible_playbook
      playbook: test/integration/default/default.yml


