---
driver:
  name: lxd_cli
## FIXME! httpd/centos7/capability issue on lxc
## https://github.com/lxc/lxd/issues/1245
## https://bugzilla.redhat.com/show_bug.cgi?id=1012952
## no drop of setfcap = 'set lxc.cap.drop = audit_control audit_write mac_admin mac_override mknod setpcap sys_admin sys_boot sys_module sys_nice sys_pacct sys_rawio sys_resource sys_time sys_tty_config'
  config:
    security.privileged: true

transport:
  name: sftp

driver_config:
    customize:
#      cpus: 2
      memory: 1024

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ansible_yum_repo: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
  require_ansible_omnibus: true
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8588}]
#  - name: ubuntu-12.04
  - name: centos-7
#  - name: centos-6
## "Failed to complete #create action: [Broken pipe] on default-alpine-34"
## do we have python2 in default image?
#  - name: alpine-3.4

suites:
  - name: default
    run_list:
    attributes:
  - name: nginx
    run_list:
## NOK
#    attributes:
#        misp_webserver: 'nginx'
    includes:
      - ubuntu-16.04
      - ubuntu-14.04
      - centos-7
    provisioner:
      name: ansible_playbook
      playbook: test/integration/nginx/default.yml



