---
driver:
  name: docker
  ## https://github.com/test-kitchen/kitchen-docker/issues/54
  use_sudo: false
  ## resources limit
  cpu: 2
  memory: 1GB
  run_options: --cpus=0.8

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
  # ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 4
  # ansible_version: 2.7.7
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ansible_cfg_path: test/vagrant/ansible.cfg
  # require_chef_omnibus: false
  require_ansible_omnibus: true
  # require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh

platforms:
  - name: centos-8
  - name: centos-7
  - name: debian-bullseye
  - name: ubuntu-20.04

suites:
  - name: default
    run_list:
    attributes:
  - name: default-HEAD
    run_list:
    attributes:
  - name: nginx
    run_list:
    attributes:
