---
driver:
  name: vagrant
  provider: <%= ENV['KITCHEN_PROVIDER'] || 'virtualbox' %>

transport:
  name: sftp

driver_config:
  customize:
    # cpus: 2
    memory: 1024

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
  # ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ansible_cfg_path: test/vagrant/ansible.cfg

platforms:
  - name: centos-8
  - name: centos-7
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8589}]
  - name: debian-bullseye
  - name: ubuntu-20.04

suites:
  - name: default
    run_list:
    attributes:
  - name: default-HEAD
    run_list:
    attributes:
  - name: nginx
    run_list:
    attributes:
      misp_webserver: 'nginx'
