---

- name: RedHat | Ensure selinux context for MISP httpd directories
  ansible.builtin.command: "chcon -R -t httpd_sys_rw_content_t {{ item }}"  # noqa no-changed-when
  # community.general.sefcontext:
  #   target: "{{ item }}(/.*)?"
  #   setype: httpd_sys_rw_content_t
  #   state: present
  with_items:
    - "{{ misp_rootdir }}/app/files"
    - "{{ misp_rootdir }}/app/files/terms"
    - "{{ misp_rootdir }}/app/files/scripts/tmp"
    - "{{ misp_rootdir }}/app/Plugin/CakeResque/tmp"
    - "{{ misp_rootdir }}/app/tmp"
    - "{{ misp_rootdir }}/app/tmp/cache/persistent"
    - "{{ misp_rootdir }}/app/webroot/img/flags"
    - "{{ misp_rootdir }}/app/webroot/img/custom"
    - "{{ misp_rootdir }}/.gnupg"
    - "{{ misp_rootdir }}/app/Config/config.php"
